name: Kernel Patches Update

on:
  schedule:
    - cron: 0 0 * * *

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update kernel patches
        run: |
             cd $GITHUB_WORKSPACE
             cd sys-kernel/surface-sources/
             ./update-sources.sh


      - name: Commit & Push changes to Gitea
        run: |
          git config user.name "Gitea CI"
          git config user.email "ci@gitea.local"

          git add sys-kernel/surface-sources/files/.
          git commit -m "Update kernel patches" || echo "No changes to commit"

          # Force the remote to point to Gitea
          git remote set-url origin https://ci-bot:${{ secrets.GITEA_TOKEN }}@gitea.metalrip.com/MetalRip/metalrip-overlay.git

          git push origin main
